### ISSUE TITLE
sdk能否加入jcenter？？？？

### ISSUE THREAD

**Issue by rongloveyan** [TuSDK/TuSDK-for-Android#1]
能否做到可以在build.gradle里加入compile 'com.XXXXXXXX:1.8.12'，就可以下载sdk aar包？？？

**Comment by idealhack** [comment]
感谢反馈，此功能已经通过 jitpack.io 实现，但是由于其它一些原因暂未正式发布。我们会尽快推出。

**Comment by jitpack-io** [comment]
Hi guys
I believe this is related to: https://github.com/jitpack/jitpack.io/issues/197
Happy to submit a PR with a fix if you are interested.

**Comment by idealhack** [comment]
此问题已长期不活跃所以关闭，如有人认为仍需要此功能请 reopen。
