### ISSUE TITLE
把keepattributes InnerClasses去掉吧

### ISSUE THREAD

**Issue by CyberTianzun** [TuSDK/TuSDK-for-Android#2]
你们的混淆配置中的这种全局的配置都应该删掉吧
对我原先代码的侵入性太高了，做得再好我也宁愿选择别的sdk

-keepattributes InnerClasses

**Comment by idealhack** [comment]
您好，项目中附带的混淆规则是起参考作用，可能需要依照自己项目情况修改。

**Comment by CyberTianzun** [comment]
我去掉了这句调起sdk就是白板

我增加了

```
-keep class org.lasque.tusdk.**$* { *; }

-keep class android.support.**$* { *; }
-keep class org.apache.commons.**$* { *; }
-keep class com.nostra13.universalimageloader.**$* { *; }
-keep class it.sephiroth.android.library.exif2.**$* { *; }
```

这些，好像没有效果，依然是白板，是有别的内部类的调用吗？

**Comment by idealhack** [comment]
谢谢反馈，我们正在测试。

**Comment by allen2peace** [comment]
@cnzx219 您好，我们之前没有针对单独类写规则，目前还在调查是哪里引起的问题

**Comment by allen2peace** [comment]
@cnzx219  您好，由于我们 SDK 中使用了反射机制，而其中的 Class$getDeclaredClasses() 方法来需要设置  -keepattributes InnerClasses 声明才能起作用，因此目前无法删除这条规则；

我们后续会继续想办法去掉类似规则，您还有其它什么建议么？

**Comment by CyberTianzun** [comment]
我猜测也是有使用反射的地方，我反复反编译了一下感觉其实有-keepattributes InnerClasses的话问题不大。我之前的话可能说太重，不过我还是希望sdk代码是低侵入性的。tusdk是很棒的sdk。
